### ISSUE TITLE
Git tagging releases.

### ISSUE THREAD

**Issue by jweakley** [wildland/wildland_dev_tools#20]

**Comment by jweakley** [comment]
## EXAMPLE VERSION FILE

This would be in a root level file `app-version.json`.

```
{
  "version": "x.x.x"
}
```

## PROCESS

If the application has a version file it will bump the version number by  prompting the user for what kind of bump (major, minor, patch).
- Commit the change and push it to github.
- Create a release on github using the name `vx.x.x` as the format. Example `1.0.1` would be `v1.0.1`
- It push this to master and staging.
- It would promote newly updated deployed staging to production.
- If there is no file it falls back to todays date `yyyymmdd`

**Comment by jweakley** [comment]
We may want to address the concept of release candidates as well.

**Comment by Samsinite** [comment]
For tagging, we need to create and push a RC tag during the `deploy_master_to_staging` routine. And during the `promote_staging_to_production` routine, create a release tag.

**Comment by jweakley** [comment]
This was fixed in https://github.com/wildland/wildland_dev_tools/tree/v0.8.0
